# WARNING: this file was autogenerated by generate-included-image.js
# using
#   npm run add:included -- 4.0.1 khulnasoft/browsers:node13.6.0-chrome80-ff72
set e+x

LOCAL_NAME=khulnasoft/included:4.0.1
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
