# WARNING: this file was autogenerated by generate-included-image.js
# using
#   npm run add:included -- 4.2.0 khulnasoft/browsers:node12.13.0-chrome80-ff74
set e+x

LOCAL_NAME=khulnasoft/included:4.2.0
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
