version: '3.8'

# REPO_PREFIX is used in CI to deploy to other docker registries than dockerhub.

services:
  factory:
    image: ${REPO_PREFIX-}khulnasoft/factory
    build:
      dockerfile: factory.Dockerfile
      target: factory
      context: .
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        FACTORY_DEFAULT_NODE_VERSION: ${FACTORY_DEFAULT_NODE_VERSION}
      tags:
        - ${REPO_PREFIX-}khulnasoft/factory:latest
        - ${REPO_PREFIX-}khulnasoft/factory:${FACTORY_VERSION}
    command: node -v

  included:
    image: ${REPO_PREFIX-}khulnasoft/included
    build:
      target: included_image
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION}
        FACTORY_VERSION: ${FACTORY_VERSION}
        CHROME_VERSION: ${CHROME_VERSION}
        KHULNASOFT_VERSION: ${KHULNASOFT_VERSION}
        EDGE_VERSION: ${EDGE_VERSION}
        FIREFOX_VERSION: ${FIREFOX_VERSION}
        YARN_VERSION: ${YARN_VERSION}
        # WEBKIT_VERSION: ${WEBKIT_VERSION}
      tags:
        - ${REPO_PREFIX-}khulnasoft/included:latest
        - ${REPO_PREFIX-}khulnasoft/included:${INCLUDED_IMAGE_SHORT_TAG}
        - ${REPO_PREFIX-}khulnasoft/included:${INCLUDED_IMAGE_TAG}
    command: node -v

  browsers:
    image: ${REPO_PREFIX-}khulnasoft/browsers
    build:
      target: default_image
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION}
        FACTORY_VERSION: ${FACTORY_VERSION}
        YARN_VERSION: ${YARN_VERSION}
        CHROME_VERSION: ${CHROME_VERSION}
        FIREFOX_VERSION: ${FIREFOX_VERSION}
        EDGE_VERSION: ${EDGE_VERSION}
      tags:
        - ${REPO_PREFIX-}khulnasoft/browsers:latest
        - ${REPO_PREFIX-}khulnasoft/browsers:${BROWSERS_IMAGE_TAG}
    command: node -v

  base:
    image: ${REPO_PREFIX-}khulnasoft/base
    build:
      target: default_image
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION}
        FACTORY_VERSION: ${FACTORY_VERSION}
        YARN_VERSION: ${YARN_VERSION}
      tags:
        - ${REPO_PREFIX-}khulnasoft/base:latest
        - ${REPO_PREFIX-}khulnasoft/base:${BASE_IMAGE_TAG}
    command: node -v

  ## Unused images that we could release in the future if we choose.
  chrome:
    image: '${REPO_PREFIX-}khulnasoft/chrome'
    build:
      target: default_image
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION}
        FACTORY_VERSION: ${FACTORY_VERSION}
        CHROME_VERSION: ${CHROME_VERSION}
      tags:
        - ${REPO_PREFIX-}khulnasoft/chrome:${CHROME_VERSION}
    command: google-chrome --version

  edge:
    image: ${REPO_PREFIX-}khulnasoft/edge
    build:
      target: default_image
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION}
        FACTORY_VERSION: ${FACTORY_VERSION}
        EDGE_VERSION: ${EDGE_VERSION}
      tags:
        - ${REPO_PREFIX-}khulnasoft/edge:${EDGE_VERSION}
    command: edge --version

  firefox:
    image: ${REPO_PREFIX-}khulnasoft/firefox
    build:
      target: default_image
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION}
        FACTORY_VERSION: ${FACTORY_VERSION}
        FIREFOX_VERSION: ${FIREFOX_VERSION}
      tags:
        - ${REPO_PREFIX-}khulnasoft/firefox:${FIREFOX_VERSION}
    command: firefox --version

  # webkit:
  #   image: ${REPO_PREFIX-}khulnasoft/webkit
  #   build:
  #     target: default_image
  #     context: .
  #     args:
  #       FACTORY_VERSION: ${FACTORY_VERSION}
  #       WEBKIT_VERSION: ${WEBKIT_VERSION}
  #     tags:
  #     - ${REPO_PREFIX-}khulnasoft/webkit:${WEBKIT_VERSION}
  #   command: webkit --version

  khulnasoft:
    image: ${REPO_PREFIX-}khulnasoft/khulnasoft
    build:
      target: default_image
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION}
        FACTORY_VERSION: ${FACTORY_VERSION}
        KHULNASOFT_VERSION: ${KHULNASOFT_VERSION}
      tags:
        - ${REPO_PREFIX-}khulnasoft/khulnasoft:${KHULNASOFT_VERSION}
    command: khulnasoft verify

  khulnasoft-chrome:
    image: ${REPO_PREFIX-}khulnasoft/khulnasoft-chrome
    build:
      target: default_image
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION}
        FACTORY_VERSION: ${FACTORY_VERSION}
        KHULNASOFT_VERSION: ${KHULNASOFT_VERSION}
        CHROME_VERSION: ${CHROME_VERSION}
      tags:
        - ${REPO_PREFIX-}khulnasoft/khulnasoft-chrome:khulnasoft-${KHULNASOFT_VERSION}-chrome-${CHROME_VERSION}
    command: node -v

  khulnasoft-edge:
    image: ${REPO_PREFIX-}khulnasoft/khulnasoft-edge
    build:
      target: default_image
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION}
        FACTORY_VERSION: ${FACTORY_VERSION}
        KHULNASOFT_VERSION: ${KHULNASOFT_VERSION}
        EDGE_VERSION: ${EDGE_VERSION}
      tags:
        - ${REPO_PREFIX-}khulnasoft/khulnasoft-edge:khulnasoft-${KHULNASOFT_VERSION}-edge-${EDGE_VERSION}
    command: node -v

  khulnasoft-firefox:
    image: ${REPO_PREFIX-}khulnasoft/khulnasoft-firefox
    build:
      target: default_image
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION}
        FACTORY_VERSION: ${FACTORY_VERSION}
        KHULNASOFT_VERSION: ${KHULNASOFT_VERSION}
        FIREFOX_VERSION: ${FIREFOX_VERSION}
      tags:
        - ${REPO_PREFIX-}khulnasoft/khulnasoft-firefox:khulnasoft-${KHULNASOFT_VERSION}-firefox-${FIREFOX_VERSION}
    command: node -v

  ## Test image
  test-node-default:
    build:
      target: default_image
      context: .
      args:
        FACTORY_VERSION: ${FACTORY_VERSION}
    command: node -v
