# WARNING: this file was autogenerated by generate-included-image.js
# using
#   npm run add:included -- 4.9.0 khulnasoft/browsers:node12.16.2-chrome81-ff75
set e+x

LOCAL_NAME=khulnasoft/included:4.9.0
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
